[theme]
base = "dark"
primaryColor = "#00d4ff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#020205"
textColor = "#f0f0f5"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
